baseURL = "http://example.org/"
languageCode = "en-us"
title = "Technical Demo"
theme = "okf"


[mediaTypes]        
  [mediaTypes."application/atom"]
    suffixes = ["xml"]
  [mediaTypes."application/json"]
    suffixes = ["json"]

[outputFormats]
  [outputFormats.Atom]
    mediaType = "application/atom"
    baseName = "atom"
    isPlainText = false
  [outputFormats.Json]
    mediaType = "application/json"
    baseName = "section"
  

[outputs]
section = [ "HTML", "Atom", "Json" ]
