baseURL = "https://lislis.github.io/tech-demo"
languageCode = "de-DE"
title = "Technical Demo"
theme = "okf"
publishDir = "docs"

[mediaTypes]        
  [mediaTypes."application/atom"]
    suffixes = ["xml"]
  [mediaTypes."application/json"]
    suffixes = ["json"]

[outputFormats]
  [outputFormats.Atom]
    mediaType = "application/atom"
    baseName = "atom"
    isPlainText = false
  [outputFormats.Json]
    mediaType = "application/json"
    baseName = "index"
  
[outputs]
home = ["HTML", "Json"]
section = [ "HTML", "Atom", "Json" ]
